### PR TITLE
Bump up body font weight for readability/accessibility

### PR DESCRIPTION
**Pull request by kden**
See discussion at
[Certbot Issue 8052](https://github.com/certbot/certbot/issues/8052)

This bumps up the thickness of the body text, hyperlinks, and h1 links to make the documentation more accessible to people with vision difficulties.

### CODE REVIEW

**Comment by bmw** [comment]
I'm having some trouble testing this.

I updated a branch of our website repo to use your fork at https://github.com/certbot/website/commit/25f28e4789e1d30e794ff561860ea52067deeac3. Travis built the site with this change and pushed the result to https://github.com/certbot/website-builds/tree/font-weight. You can run this site locally if you want by following the instructions at https://github.com/certbot/website#travis-builds.

Nothing seems to have changed though. In fact, if you run `pip install` this way, the `sass` directory doesn't even seem to be included in the installed package. This is true both when using your fork and when installing from the `master` branch of this repo.

Any ideas what's causing the values to differ from the RTD default in this case? Does something else in this repo need to be modified? Did I give you a bad pointer to this repo and it's something in https://github.com/certbot/website/ instead? I'm personally not immediately sure.

**Comment by kden** [comment]
I've been trying to go through the website instructions using Docker but am having some trouble.  I notice that when it builds the Docker container and runs gulp build, it runs docs.js docs_make which runs _docs.sh install which contains
```
    cd _docs
    source ./venv/bin/activate
    pip install --upgrade git+https://github.com/EFForg/sphinx_rtd_theme.git
```
It doesn't pass any branch or version information to the pip install upgrade command, so if this is what Travis runs, I think that the theme has to be the "live" version.  I will look a bit more to see if there is some way to pass the branch through.

**Comment by bmw** [comment]
To test this, I've just been modifying that pip install command to use your fork and branch like I did at https://github.com/certbot/website/commit/25f28e4789e1d30e794ff561860ea52067deeac3. You can also just run a similar command in Certbot's virtual environment locally and then build the docs as described at https://certbot.eff.org/docs/contributing.html to test the changes here.

Doing the latter to take a look at this, the links for things like the table of contents at https://certbot.eff.org/docs/using.html seem excessively heavy to me, but I don't have a great eye for this stuff. If it looks good to you, we should probably leave it for now.

Another thing I noticed though is the text the original reporter said had low contrast [here](https://github.com/certbot/certbot/issues/8052#issuecomment-639192564) seems to be unmodified. Is this intentional?

Finally, I think we should unminify the CSS here. It looks my coworkers added some [comments](https://github.com/EFForg/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/static/css/badge_only.css#L43) here in the past which I'd rather not blow away.

Otherwise, this LGTM! Thanks for yet another PR @kden.

**Comment by kden** [comment]
I increased the color contrast in the side menu as pointed out in the original ticket. It looks like it is computed as part of the wrym side menu.  As a side note wyrm is a component installed as a bower dependency, but it is no longer supported; there's a discussion here about taking it out of the original sphinx_rtd_theme: https://github.com/readthedocs/sphinx_rtd_theme/issues/544.  

Also, rebuilt the css files without minifying them.

I'm also struggling with testing; in the end I set up an Apache instance locally and pointed it to the site and doc folders just to see it in a browser with relative paths.  I'm just not familiar enough with nginx yet to troubleshoot why it's not working for me.  Chrome developer tools show me that the old menu text that was #808080 had a contrast score of 3.95, which is not great, and the new color, #404040 has  contrast score of 10.37.   [WCAG level AAA requires a contrast ratio of at least 7:1 for normal text.](https://webaim.org/resources/contrastchecker/#:~:text=WCAG%202.1%20requires%20a%20contrast,4.5%3A1%20for%20large%20text.)

**Comment by bmw** [comment]
I wanted to rebuild things here myself to ensure that all the CSS changes were reflected in changes to the sass files so we don't accidentally lose changes in the future but I had issues when using the mix of pinned and unpinned dependencies here. In particular, I hit https://github.com/thoughtbot/bourbon/issues/419.

I'll probably see if someone more familiar with this stuff than me can review this PR.

**Comment by kden** [comment]
In case this helps, here are the npm ls dependency trees I have in the sphinx_rtd_theme and website projects.

[sphinx_rtd_theme_npm_ls.txt](https://github.com/EFForg/sphinx_rtd_theme/files/4794421/sphinx_rtd_theme_npm_ls.txt)
[website_npm_ls.txt](https://github.com/EFForg/sphinx_rtd_theme/files/4794431/website_npm_ls.txt)

I'm using sass executable version "Sass 3.4.23 (Selective Steve)"

Also, in order to get the uncompressed sass result, I had to run `grunt sass:dev` instead of `grunt:sass` or `grunt:build`.  Following the directions in the README.md of running `grunt:build` before filing a PR result in creating minified CSS files.

**Comment by kden** [comment]
Just checking to see if there is anything that still needs to be updated here.

**Comment by bmw** [comment]
Thanks for the ping kden, but we actually have moved away from using this.

I'm sorry I was never able to wrangle someone to review this before we migrated away.

**Comment by kden** [comment]
No worries!  Just cleaning up my queue.

**Pull request closed without merging**
